spring:
  application:
    name: file-storing-service
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

minio:
  bucket: ${MINIO_BUCKET:cosmoscan-works}

analysis:
  service:
    url: ${ANALYSIS_SERVICE_URL:http://localhost:8082}

outbox:
  poll-interval-ms: 5000

springdoc:
  api-docs:
    path: /v3/api-docs
