spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver

minio:
  endpoint: http://${MINIO_HOST}:${MINIO_PORT}
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}

server:
  port: 8081

analysis:
  service:
    url: ${ANALYSIS_SERVICE_URL}
