server:
  port: 8081

spring:
  profiles:
    active: local
  application:
    name: mission-scheduler
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: missions
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: missions

app:
  space-center-service:
    missions:
      - targetType: CONSTELLATION
        constellationName: "Орбита-1"
        cron: "0 0 */6 * * *"
      - targetType: CONSTELLATION
        constellationName: "Орбита-2"
        cron: "0 */1 * * * *"

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 30000
        loggerLevel: full
  okhttp:
    enabled: true

logging:
  level:
    ru.bauman.scheduler: DEBUG
    feign: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always